import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import { LayoutProps } from '@/types';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: './favicon.ico' },
};

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang='en'>
      <body className={cn('bg-background', inter.className)}>{children}</body>
    </html>
  );
}
